package com.lxseek.chat.plugin.market

import android.content.Context
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import java.io.IOException

/**
 * Built-in asset skill source: loads a curated skill/plugin index bundled in
 * `assets/builtin-skills-index.json` and serves offline SKILL.md bodies from
 * `assets/skills/builtin/`. Non-curated entries carry a `manifestUrl` pointing
 * to the upstream GitHub raw URL so they can be downloaded on demand.
 *
 * The index is generated by `scripts/build_builtin_skills.py` and contains
 * metadata for all 828 skills across skill-manager, ia and agent-skills-hub
 * repos, plus 49 OpenCode plugin definitions. 69 skills are curated (full
 * SKILL.md bundled offline); the rest are browse-only until downloaded.
 *
 * Two app-authored skills (`runtime-node-inkos` / `runtime-python-webnovel`)
 * are also bundled in `skills/builtin/` even though they are not part of the
 * generated index — [PluginMarket] merges their catalog metas separately via
 * [BuiltinMarketSources.fetchBuiltinSkillCatalog], and their SKILL.md bodies
 * are served from here.
 */
object BuiltinAssetSource {

    const val PREFIX = "builtin-asset"
    private const val INDEX_ASSET = "builtin-skills-index.json"
    private const val SKILLS_DIR = "skills/builtin"
    private const val PLUGINS_DIR = "plugins/builtin"

    /** App-authored skills bundled outside the generated index (bodies live in SKILLS_DIR). */
    private val APP_AUTHORED = setOf("runtime-node-inkos", "runtime-python-webnovel")

    /** GitHub raw URL base for downloading non-curated SKILL.md on demand. */
    private val REPO_BASE = mapOf(
        "skill-manager" to "https://raw.githubusercontent.com/nano-step/skill-manager/main",
        "ia" to "https://raw.githubusercontent.com/rmalan99/ia/main",
        "agent-skills-hub" to "https://raw.githubusercontent.com/legendaryabhi/agent-skills-hub/main",
    )

    private val json = Json { ignoreUnknownKeys = true }

    @Serializable
    private data class SkillIndex(
        val name: String,
        val description: String = "",
        val repo: String = "",
        val path: String = "",
        val sizeKb: Double = 0.0,
        val curated: Boolean = false,
    )

    @Serializable
    private data class PluginIndex(
        val name: String,
        val displayName: String = "",
        val description: String = "",
        val categories: List<String> = emptyList(),
        val license: String = "",
        val maintained: Boolean = false,
        val lastUpdated: String = "",
        val fileName: String = "",
    )

    /** Bundled OpenCode `.plugin.json` shape — only the fields used to compose a skill body. */
    @Serializable
    private data class BundledPluginFile(
        val displayName: String = "",
        val description: String = "",
        val installation: MarkdownSection? = null,
        val usage: MarkdownSection? = null,
    )

    @Serializable
    private data class MarkdownSection(
        val summary: String = "",
        val markdown: String = "",
    )

    @Serializable
    private data class BuiltinIndex(
        val version: Int = 0,
        val skills: List<SkillIndex> = emptyList(),
        val plugins: List<PluginIndex> = emptyList(),
    )

    /**
     * Load the bundled index from assets and convert to [MarketIndex].
     * Each skill becomes a [MarketPluginMeta] with id `builtin-asset:{name}`.
     * Curated skills have no manifestUrl (served from assets); non-curated
     * ones carry the GitHub raw URL for on-demand download.
     */
    suspend fun fetchCatalog(context: Context): MarketIndex = withContext(Dispatchers.IO) {
        val raw = readAsset(context, INDEX_ASSET)
            ?: throw IOException("Built-in index not found: $INDEX_ASSET")
        val index = json.decodeFromString<BuiltinIndex>(raw)
        val metas = index.skills.map { it.toMeta() } + index.plugins.map { it.toMeta() }
        MarketIndex(plugins = metas)
    }

    /** Whether [pluginId] (raw id, no prefix) is one of the app-authored bundled skills. */
    fun isAppAuthored(pluginId: String): Boolean = pluginId in APP_AUTHORED

    /**
     * Read a curated SKILL.md from `assets/skills/builtin/{name}.md`. App-authored
     * skill ids (e.g. `runtime-python-webnovel`) are also resolved here — their
     * bodies are bundled in the same directory even though they are not part of
     * the generated index.
     * Returns empty string if the file is not bundled (non-curated skill).
     */
    suspend fun fetchSkillBody(context: Context, pluginId: String): String = withContext(Dispatchers.IO) {
        val name = slugAfterPrefix(pluginId)
        readAsset(context, "$SKILLS_DIR/$name.md") ?: ""
    }

    /**
     * Read a bundled OpenCode `.plugin.json` from `assets/plugins/builtin/{name}.plugin.json`
     * and compose a SKILL.md-equivalent body from its installation/usage markdown sections.
     * Returns empty string when the file is not bundled.
     */
    suspend fun fetchPluginBody(context: Context, pluginId: String): String = withContext(Dispatchers.IO) {
        val name = slugAfterPrefix(pluginId)
        val raw = readAsset(context, "$PLUGINS_DIR/$name.plugin.json") ?: return@withContext ""
        val plugin = runCatching { json.decodeFromString<BundledPluginFile>(raw) }.getOrNull()
            ?: return@withContext ""
        buildString {
            plugin.displayName.takeIf { it.isNotBlank() }?.let { appendLine("# $it") ; appendLine() }
            plugin.description.takeIf { it.isNotBlank() }?.let { appendLine(it.trim()); appendLine() }
            plugin.installation?.let { section ->
                section.summary.takeIf { it.isNotBlank() }?.let { appendLine("## 安装"); appendLine(it.trim()); appendLine() }
                section.markdown.takeIf { it.isNotBlank() }?.let { appendLine(it.trim()); appendLine() }
            }
            plugin.usage?.let { section ->
                section.markdown.takeIf { it.isNotBlank() }?.let { appendLine("## 用法"); appendLine(it.trim()); appendLine() }
            }
        }.trim()
    }

    // ── Mapping ───────────────────────────────────────────────

    private fun SkillIndex.toMeta(): MarketPluginMeta {
        val isCurated = curated
        val manifestUrl = if (!isCurated) {
            REPO_BASE[repo]?.let { "$it/$path" }
        } else {
            null
        }
        return MarketPluginMeta(
            id = "$PREFIX:$name",
            name = name,
            version = "1.0.0",
            kind = MarketPluginKind.SKILL,
            description = description,
            manifestUrl = manifestUrl,
            homepage = REPO_BASE[repo]?.let { "$it/$path" },
        )
    }

    private fun PluginIndex.toMeta(): MarketPluginMeta {
        return MarketPluginMeta(
            id = "$PREFIX:plugin:$name",
            name = displayName.ifBlank { name },
            version = lastUpdated.ifBlank { "1.0.0" },
            kind = MarketPluginKind.SKILL,
            description = description,
            author = if (maintained) "maintained" else null,
        )
    }

    // ── Helpers ───────────────────────────────────────────────

    private fun slugAfterPrefix(pluginId: String): String {
        val prefixWithColon = "$PREFIX:"
        return if (pluginId.startsWith(prefixWithColon)) {
            pluginId.removePrefix(prefixWithColon).removePrefix("plugin:")
        } else {
            pluginId
        }
    }

    private fun readAsset(context: Context, path: String): String? {
        return runCatching {
            context.assets.open(path).use { it.readBytes().toString(Charsets.UTF_8) }
        }.getOrNull()
    }
}