package com.lxseek.chat.plugin.market

import android.content.Context
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import java.io.IOException

/**
 * Built-in asset skill source: loads a curated skill/plugin index bundled in
 * `assets/builtin-skills-index.json` and serves offline SKILL.md bodies from
 * `assets/skills/builtin/`. Non-curated entries carry a `manifestUrl` pointing
 * to the upstream GitHub raw URL so they can be downloaded on demand.
 *
 * The index is generated by `scripts/build_builtin_skills.py` and contains
 * metadata for all 828 skills across skill-manager, ia and agent-skills-hub
 * repos, plus 49 OpenCode plugin definitions. 69 skills are curated (full
 * SKILL.md bundled offline); the rest are browse-only until downloaded.
 */
object BuiltinAssetSource {

    const val PREFIX = "builtin-asset"
    private const val INDEX_ASSET = "builtin-skills-index.json"
    private const val SKILLS_DIR = "skills/builtin"
    private const val PLUGINS_DIR = "plugins/builtin"

    /** GitHub raw URL base for downloading non-curated SKILL.md on demand. */
    private val REPO_BASE = mapOf(
        "skill-manager" to "https://raw.githubusercontent.com/nano-step/skill-manager/main",
        "ia" to "https://raw.githubusercontent.com/rmalan99/ia/main",
        "agent-skills-hub" to "https://raw.githubusercontent.com/legendaryabhi/agent-skills-hub/main",
    )

    private val json = Json { ignoreUnknownKeys = true }

    @Serializable
    private data class SkillIndex(
        val name: String,
        val description: String = "",
        val repo: String = "",
        val path: String = "",
        val sizeKb: Double = 0.0,
        val curated: Boolean = false,
    )

    @Serializable
    private data class PluginIndex(
        val name: String,
        val displayName: String = "",
        val description: String = "",
        val categories: List<String> = emptyList(),
        val license: String = "",
        val maintained: Boolean = false,
        val lastUpdated: String = "",
        val fileName: String = "",
    )

    @Serializable
    private data class BuiltinIndex(
        val version: Int = 0,
        val skills: List<SkillIndex> = emptyList(),
        val plugins: List<PluginIndex> = emptyList(),
    )

    /**
     * Load the bundled index from assets and convert to [MarketIndex].
     * Each skill becomes a [MarketPluginMeta] with id `builtin-asset:{name}`.
     * Curated skills have no manifestUrl (served from assets); non-curated
     * ones carry the GitHub raw URL for on-demand download.
     */
    suspend fun fetchCatalog(context: Context): MarketIndex = withContext(Dispatchers.IO) {
        val raw = readAsset(context, INDEX_ASSET)
            ?: throw IOException("Built-in index not found: $INDEX_ASSET")
        val index = json.decodeFromString<BuiltinIndex>(raw)
        val metas = index.skills.map { it.toMeta() } + index.plugins.map { it.toMeta() }
        MarketIndex(plugins = metas)
    }

    /**
     * Read a curated SKILL.md from `assets/skills/builtin/{name}.md`.
     * Returns empty string if the file is not bundled (non-curated skill).
     */
    suspend fun fetchSkillBody(context: Context, pluginId: String): String = withContext(Dispatchers.IO) {
        val name = slugAfterPrefix(pluginId)
        readAsset(context, "$SKILLS_DIR/$name.md") ?: ""
    }

    // ── Mapping ───────────────────────────────────────────────

    private fun SkillIndex.toMeta(): MarketPluginMeta {
        val isCurated = curated
        val manifestUrl = if (!isCurated) {
            REPO_BASE[repo]?.let { "$it/$path" }
        } else {
            null
        }
        return MarketPluginMeta(
            id = "$PREFIX:$name",
            name = name,
            version = "1.0.0",
            kind = MarketPluginKind.SKILL,
            description = description,
            manifestUrl = manifestUrl,
            homepage = REPO_BASE[repo]?.let { "$it/$path" },
        )
    }

    private fun PluginIndex.toMeta(): MarketPluginMeta {
        return MarketPluginMeta(
            id = "$PREFIX:plugin:$name",
            name = displayName.ifBlank { name },
            version = lastUpdated.ifBlank { "1.0.0" },
            kind = MarketPluginKind.SKILL,
            description = description,
            author = if (maintained) "maintained" else null,
        )
    }

    // ── Helpers ───────────────────────────────────────────────

    private fun slugAfterPrefix(pluginId: String): String {
        val prefixWithColon = "$PREFIX:"
        return if (pluginId.startsWith(prefixWithColon)) {
            pluginId.removePrefix(prefixWithColon).removePrefix("plugin:")
        } else {
            pluginId
        }
    }

    private fun readAsset(context: Context, path: String): String? {
        return runCatching {
            context.assets.open(path).use { it.readBytes().toString(Charsets.UTF_8) }
        }.getOrNull()
    }
}